# Generated by Django 2.2.14 on 2020-08-20 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gitft',
            new_name='Gift',
        ),
    ]
